// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbc43HMj-jDjkApzHKjep2Up_fwrckSsQ',
    appId: '1:240050382692:web:2b11a5b604b7679273bc71',
    messagingSenderId: '240050382692',
    projectId: 'community-market-place-303f4',
    authDomain: 'community-market-place-303f4.firebaseapp.com',
    storageBucket: 'community-market-place-303f4.firebasestorage.app',
    measurementId: 'G-8HHRK2WPKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByI2vn0x6UxeyhqE-ODJDdRwUCM0hKHg4',
    appId: '1:240050382692:android:43f5e7e7c1960e4173bc71',
    messagingSenderId: '240050382692',
    projectId: 'community-market-place-303f4',
    storageBucket: 'community-market-place-303f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD7FRkuXAH-BHfRmXZM7foBqvHCSwGvEo',
    appId: '1:240050382692:ios:ac15e4fcdb2ea42b73bc71',
    messagingSenderId: '240050382692',
    projectId: 'community-market-place-303f4',
    storageBucket: 'community-market-place-303f4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD7FRkuXAH-BHfRmXZM7foBqvHCSwGvEo',
    appId: '1:240050382692:ios:ac15e4fcdb2ea42b73bc71',
    messagingSenderId: '240050382692',
    projectId: 'community-market-place-303f4',
    storageBucket: 'community-market-place-303f4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbc43HMj-jDjkApzHKjep2Up_fwrckSsQ',
    appId: '1:240050382692:web:7412dacf012f76d473bc71',
    messagingSenderId: '240050382692',
    projectId: 'community-market-place-303f4',
    authDomain: 'community-market-place-303f4.firebaseapp.com',
    storageBucket: 'community-market-place-303f4.firebasestorage.app',
    measurementId: 'G-4RQ9HKBMZ2',
  );
}
